=== lovettchris/xmldiff/src/Common/Updates.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="updates">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="application">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string">
                <xs:annotation>
                  <xs:documentation>The name of the application being updated.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="location" type="xs:string">
                <xs:annotation>
                  <xs:documentation>The location of the update xml page.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="download" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Location of the download page.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="installer" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Location of the installation page.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="history" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Location of the page showing update history.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="frequency" type="xs:string" >
                <xs:annotation>
                  <xs:documentation>The frequency we need to check for updates to the application, any valid TimeSpan.</xs:documentation>
                </xs:annotation>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" name="version">
          <xs:annotation>
            <xs:documentation>This element describes a new version of the application.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded" >
              <xs:element name="feature" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Description of a new feature added in this version.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="bug" type="xs:string" >
                <xs:annotation>
                  <xs:documentation>Description of a bug fixed in this version.</xs:documentation>
                </xs:annotation>
              </xs:element>
            </xs:choice>
            <xs:attribute name="number" type="xs:string" use="required">
              <xs:annotation>
                <xs:documentation>The version number.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== lovettchris/xmldiff/src/Common/changes.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="Updates.xslt"?>
<updates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Updates.xsd">
  <application>
    <title>Microsoft XML Diff</title>
    <location>https://raw.githubusercontent.com/lovettchris/xmldiff/master/src/Common/changes.xml</location>
    <download>https://www.nuget.org/packages/LovettSoftware.XmlDiff</download>
    <installer>https://www.nuget.org/packages/LovettSoftware.XmlDiff</installer>
    <history>https://github.com/microsoft/XmlNotepad/blob/master/src/Updates/Updates.xml</history>
    <frequency>1.00:00:00</frequency>
  </application>
  <version number="1.1.0">
    <feature>Thanks to Mark Roberts for a cool new feature that omits identical output to make the diff HTML output scale better on huge XML files.</feature>
  </version>
  <version number="1.0.8">
    <bug>Add back strong naming for XmlDiffPatch.dll</bug>
  </version>
  <version number="1.0.7">
    <feature>Add .net 7.0 libraries.</feature>
    <bug>Exception in DifferencesSideBySideAsHtml</bug>
  </version>
  <version number="1.0.5">
    <feature>Code sign assemblies.</feature>
    <feature>Add .NET 6.0.</feature>
  </version>
  <version number="1.0.4">
    <feature>Add some unit tests.</feature>
    <bug>Fix premature close of streams in XmlDiff.OpenFragments</bug>
  </version>
  <version number="1.0.3">
    <bug>Fixes to HTML legend</bug>
  </version>
</updates>
